language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"
    - APCU_PECL_VERSION="apcu"
    - TESTS_LAMINAS_CACHE_APCU_ENABLED=true

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
        - APCU_PECL_VERSION="apcu-4.0.8"
    - php: 5.6
      env:
        - DEPS=latest
        - APCU_PECL_VERSION="apcu-4.0.11"
    - php: 7.0
      env:
        - DEPS=lowest
        - APCU_PECL_VERSION="apcu-5.1.2"
    - php: 7.0
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
        - APCU_PECL_VERSION="apcu-5.1.7"
    - php: 7.1
      env:
        - DEPS=latest
        - TEST_COVERAGE=true
    - php: 7.2
      env:
        - DEPS=lowest
        - APCU_PECL_VERSION="apcu-5.1.10"
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.3
      env:
        - DEPS=lowest
        - APCU_PECL_VERSION="apcu-5.1.10"
    - php: 7.3
      env:
        - DEPS=latest
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - DEPS=latest
        - CS_CHECK=true
        - TEST_COVERAGE=true

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - if [[ $APCU_PECL_VERSION != '' ]]; then
      echo "yes\nno\n" | pecl install -f $APCU_PECL_VERSION || return 0 ;
      sed -i 's/extension="apcu.so"//' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ;
    fi ;
  - if [[ $APCU_PECL_VERSION != '' ]]; then
      phpenv config-add .ci/apcu.ini ;
    fi ;
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - stty cols 120 && composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer run-script test-coverage -- --verbose ; else composer run-script test -- --verbose ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry vendor/bin/php-coveralls -v ; fi

notifications:
  email: false
